title: KiwiChat
subtitle: IRC WebChat
logo: "/assets/images/kiwichat.png"
email: contact@kiwichat.ml
description: >- # this means to ignore newlines until "baseurl:"
  Custom KiwiChat WordPress Plugin Generator
url: "https://app-oszkar.github.io/blog/"
twitter_username: showchat
github_username: showchat
minimal_mistakes_skin: air
search: true
teaser: /assets/images/blog-1200x400.png

# Build settings
markdown: kramdown
remote_theme: kiwichat/minimal-mistakes
# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Europe/Madrid # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "ShowChat"
  avatar : "/assets/images/headshots/kiwichat.png"
  bio    : "I am a nomadic software engineer, always looking for the next challenge; no task is too frightening or too difficult."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://showchat.tk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/showchat"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/showchat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kiwichat"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/showchat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kiwichat"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/showchat"
      
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      excerpt_separator: <!--more-->
      sidebar:
        nav: "blog"      
      
      

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-KIWICHAT"
    anonymize_ip: false # default


staticman:
  repository : "app-oszkar/blog" # GitHub username/repository eg. 
  branch     : "master" # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : "https://ai-kiwichat.herokuapp.com/v3/entry/github/" # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"

 # reCaptcha
  # Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
  reCaptcha:
    enabled: false
    siteKey: "6LczWUwdAAAAADV0roSgHNr6BVOC0hx-8lVGFSfh"
    # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
    # For more information, https://staticman.net/docs/encryption
    secret: "V0Bar17DP0ejv5dszJz4pVcqU9oKPRfu1FyQOAb0BFkideBYmiAcOtea+NQ8IzQxFmqVLWARd3hvpv8p3Shrfv9mNwol3mcwcb1ZMZRHu66jk6Y7yHhWOi4ZPtO9AESzh6/wWHKxn+c8f2UpmMgZPIJJXzmnRfJlUKJT0tPt1sw="
    
